#!/bin/bash
# Quick Reference Guide for 3-Model Hyperparameter Tuning
# =========================================================

echo "========================================================================"
echo "PNN_STEC: Three-Model Hyperparameter Tuning Quick Reference"
echo "========================================================================"
echo ""
echo "Three Models Ready for Cluster Hyperparameter Tuning:"
echo ""
echo "1. BayesianResNetSTEC      - Hybrid ResNet + Bayesian head (~500K params)"
echo "2. AttentionMLP_BNN_NLL    - Lightweight Attention + Bayesian head (~150-500K params)"
echo "3. FactorizedSTEC          - Physics-based VTEC × MF (~50-200K params)"
echo ""
echo "========================================================================"
echo "QUICK START"
echo "========================================================================"
echo ""
echo "Launch all three model sweeps at once:"
echo "  cd /cluster/work/igp_psr/arrueegg/WP4/PNN_STEC"
echo "  sbatch hp_search/run_3models_sweep_cluster.sh"
echo ""
echo "Or launch individual sweeps:"
echo "  sbatch hp_search/sweep_bayesresnet_cluster.sh 5    # 5 agents"
echo "  sbatch hp_search/sweep_attention_cluster.sh 4      # 4 agents"
echo "  sbatch hp_search/sweep_factorized_cluster.sh 4     # 4 agents"
echo ""
echo "========================================================================"
echo "MONITORING"
echo "========================================================================"
echo ""
echo "Check running jobs:"
echo "  squeue -u \$USER"
echo ""
echo "View logs:"
echo "  tail -f hp_search/logs/sweep_*.out"
echo "  tail -f hp_search/logs/sweep_bayesresnet_*.out"
echo "  tail -f hp_search/logs/sweep_attention_*.out"
echo "  tail -f hp_search/logs/sweep_factorized_*.out"
echo ""
echo "Check sweep IDs:"
echo "  cat hp_search/logs/BayesianResNetSTEC_sweep_id.txt"
echo "  cat hp_search/logs/AttentionMLP_BNN_NLL_sweep_id.txt"
echo "  cat hp_search/logs/FactorizedSTEC_sweep_id.txt"
echo ""
echo "W&B Dashboard:"
echo "  https://wandb.ai/your-entity/PNN_STEC_Cluster"
echo ""
echo "========================================================================"
echo "CONFIGURATION FILES"
echo "========================================================================"
echo ""
echo "Base configs (cluster-compatible):"
echo "  config/config_cluster_BayesianResNetSTEC.yaml"
echo "  config/config_cluster_AttentionMLP_BNN_NLL.yaml"
echo "  config/config_cluster_FactorizedSTEC.yaml"
echo ""
echo "Sweep configs (W&B search spaces):"
echo "  config/wandb_sweep_config_BayesianResNetSTEC_cluster.yaml"
echo "  config/wandb_sweep_config_AttentionMLP_BNN_NLL_cluster.yaml"
echo "  config/wandb_sweep_config_FactorizedSTEC_cluster.yaml"
echo ""
echo "========================================================================"
echo "KEY HYPERPARAMETERS"
echo "========================================================================"
echo ""
echo "BayesianResNetSTEC:"
echo "  - hidden_dim: [256, 512, 1024]"
echo "  - num_layers: [3, 4, 5]"
echo "  - prior_sigma: [0.01, 0.05, 0.1]"
echo "  - KL weight: [0.01, 0.05, 0.1]"
echo ""
echo "AttentionMLP_BNN_NLL:"
echo "  - hidden_dim: [128, 256, 512]"
echo "  - num_layers: [2, 3, 4]"
echo "  - num_heads: [4, 8]"
echo "  - dropout: [0.0, 0.1, 0.2]"
echo "  - KL weight: [0.01, 0.05]"
echo ""
echo "FactorizedSTEC:"
echo "  - vtec_hidden: [128, 256]"
echo "  - geom_hidden: [64, 128]"
echo "  - vtec_layers: [3, 4]"
echo "  - geom_layers: [2, 3]"
echo "  - KL weight: [0.005, 0.01, 0.02]"
echo ""
echo "========================================================================"
echo "EXPECTED PERFORMANCE (Validation MAE)"
echo "========================================================================"
echo ""
echo "BayesianResNetSTEC:    2.5-3.0 TECU (best overall)"
echo "AttentionMLP_BNN_NLL:  2.8-3.2 TECU (good efficiency)"
echo "FactorizedSTEC:        3.0-3.5 TECU (interpretable)"
echo ""
echo "========================================================================"
echo "DOCUMENTATION"
echo "========================================================================"
echo ""
echo "Detailed sweep guide:"
echo "  hp_search/README_3MODELS_SWEEP.md"
echo ""
echo "Implementation summary:"
echo "  IMPLEMENTATION_SUMMARY_3MODELS.md"
echo ""
echo "Model verification:"
echo "  python tests/verify_three_models.py"
echo ""
echo "========================================================================"
echo "TROUBLESHOOTING"
echo "========================================================================"
echo ""
echo "Sweep fails to initialize:"
echo "  - Check W&B login: wandb login"
echo "  - Verify configs exist: ls -l config/*_cluster.yaml"
echo ""
echo "Out of memory:"
echo "  - Reduce batch size in base config (1024 → 512)"
echo "  - Reduce hidden_dim in sweep config"
echo ""
echo "Slow training:"
echo "  - Verify data on scratch: check data.move_to_scratch in config"
echo "  - Reduce val_size: 1M → 500K"
echo ""
echo "Resume/add agents to existing sweep:"
echo "  SWEEP_ID=\$(cat hp_search/logs/MODEL_NAME_sweep_id.txt)"
echo "  wandb agent \$SWEEP_ID"
echo ""
echo "========================================================================"
echo "ESTIMATED TIME"
echo "========================================================================"
echo ""
echo "Per run:       2-6 hours (depending on model size)"
echo "Total runs:    ~200 (across all models)"
echo "Sweep duration: 1-3 days (with parallel agents)"
echo ""
echo "========================================================================"
