# Debug configuration for quick testing
project_name: "PNN_STEC"
output_dir: "experiments/"
year: 2024
doy: 182
mode: pretrain
random_seed: 42
debug: False  
debug_single_batch: True  # Debug mode: only process one batch
cluster: False

wandb:
  offline: True

target: "stec"

data:
  GNSS_data_path: "/home/space/data/iono/STEC_DB_CASDCB"
  use_agg_h5: True
  scratch_dir: "/scratch2/arrueegg/WP4/PNN_STEC/data/"
  SWI_data_path: "/home/space/data/iono/SWI/"
  move_to_scratch: True
  every_x_doy: 1
  use_SWI: True
  SH_degree: 0
  min_elevation: 5.0
  max_elevation: 90.0
  shuffle: True
  train_subset_size: 500_000
  val_size: 1_000_000
  test_size: 10_000_000

model:
  model_type: BayesianResNetSTEC
  hidden_dim: 256
  num_layers: 2
  prior_sigma: 0.05
  dropout_rate: 0.0
  
training:
  loss_function: "GaussianNLLLoss"
  loss_weight: 1.0
  
  kl_annealing:
    enabled: true
    warmup_epochs: 5
    start_weight: 0.0
    end_weight: 0.1
  
  target_weighting:
    enabled: false
    weight_function: "linear"
  
  optimizer: "Adam"
  weight_decay: 0.0
  standardize_targets: False
  log_target: False
  log_space_point: "mean"

pretrain:
  epochs: 2
  batchsize: 512
  num_workers: 4
  prefetch_factor: 2
  learning_rate: 0.01
  scheduler: ReduceLROnPlateau
  scheduler_step_size: 2
  early_stopping: false
  patience: 20
  save_model_every_epoch: False

finetune:
  epochs: 1
  num_workers: 4
  learning_rate: 0.001
  scheduler: ReduceLROnPlateau
  scheduler_step_size: 1
