# General configuration
project_name: "PNN_STEC"
output_dir: "experiments/"
year: 2023
doy: 1
mode: pretrain # pretrain, finetune
random_seed: 42
debug: True

target: "stec" # stec or vtec

data:
  GNSS_data_path: "/home/space/data/IONO/STEC_DB_CASDCB"
  use_agg_h5: True
  scratch_dir: "/scratch2/arrueegg/WP4/PNN_STEC/data/"
  SWI_data_path: "/home/space/data/IONO/SWI/"
  move_to_scratch: True # Whether to move data to scratch for faster access
  sampling: ultra # all semi medium hard extreme ultra
  every_x_doy: 40 # Use every x day of year (1 = all, 2 = every second day, etc.)
  use_SWI: True # Whether to use Space Weather Indices as input data
  SH_degree: 5
  min_elevation: 5.0
  max_elevation: 90.0
  shuffle: True
  train_subset_size: 10_000_000 # Number of samples to use per epoch

split:
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

model:
  model_type: MLP_NLL # BNN_NLL, BNN_mse, BranchMLP, Branch_BNN_NLL, MLP_MCDropout_NLL, MLP_MCDropout_mse, MLP_DE, MLP
  
training:
  loss_function: "GaussianNLLLoss"  # Loss function: MSELoss, MAELoss, HuberLoss, LaplaceLoss, GaussianNLLLoss,ProfileLoss
  loss_weight: 0.0
  optimizer: "Adam"             # SGD, Adam, AdamW
  weight_decay: 0.0             # Weight decay for regularization

pretrain:
  epochs: 1
  batchsize: 512
  num_workers: 0
  learning_rate: 0.001
  scheduler: StepLR            # Scheduler: none, step_lr, cosine_annealing
  scheduler_step_size: 10       # Step size for scheduler (reduces lr every X epochs)

  early_stopping: true          # Whether to use early stopping
  patience: 5                   # Patience for early stopping
  save_model_every_epoch: False # Whether to save the model every epoch

finetune:
  epochs: 5
  num_workers: 8
  learning_rate: 0.001
  scheduler: StepLR            # Scheduler: none, step_lr, cosine_annealing
  scheduler_step_size: 10       # Step size for scheduler (reduces lr every X epochs)


