project: pnn_stec
method: grid
name: MLP_MSE Sweep

parameters:
  model.model_type:
    value: MLP
  model.hidden_dim:
    values: [256, 512, 1024]
  model.num_layers:
    values: [4]
  model.learning_rate:
    values: [0.0001, 0.0005, 0.001, 0.005]
  model.loss_fn:
    value: MSELoss
  scheduler.type:
    value: CosineAnnealingLR
  training.num_epochs:
    value: 100
  training.batch_size:
    values: [512, 1024]

run_cap: 50
