program: scripts/wandb_run_wrapper.py
method: grid
metric:
  goal: minimize
  name: val_MAE

parameters:
  model.model_type:
    values: ['AttentionMLP_NLL']
  
  model.hidden_dim:
    values: [512, 1024]
  
  model.num_layers:
    values: [3, 4]
  
  model.num_heads:
    values: [4]
  
  pretrain.learning_rate:
    values: [0.0001, 0.0005, 0.001, 0.005]
  
  training.loss_function:
    values: ['GaussianNLLLoss']
  
  pretrain.epochs:
    values: [100]
  
  pretrain.batchsize:
    values: [512]

run_cap: 50
