program: scripts/wandb_run_wrapper.py
method: grid
metric:
  goal: minimize
  name: val_MAE

parameters:
  model.model_type:
    values: ['AttentionMLP_BNN_NLL']
  
  model.hidden_dim:
    values: [512, 1024]
  
  model.num_layers:
    values: [4]
  
  model.num_heads:
    values: [4]
  
  model.prior_sigma:
    values: [0.05, 0.1]

  data.SH_degree:
    values: [0, 5, 16]
  
  pretrain.learning_rate:
    values: [0.0001, 0.0005, 0.001, 0.005, 0.01]
  
  training.loss_function:
    values: ['GaussianNLLLoss']
  
  pretrain.epochs:
    values: [100]
  
  pretrain.batchsize:
    values: [512, 1024, 2048]

run_cap: 50
