"""The register of deliberate divergences between the rebuilt pipeline and the submitted
paper, and the harness that measures what each one costs.

The rebuild changes some published numbers on purpose - a bug fix, a reconciled default,
a corrected scoring rule. That is expected and fine. What is not fine is a number moving
for a reason nobody named: `docs/rebuild_plan.md` (§8, rule 2) is explicit that "a
difference is never resolved by making the new code match the old" and that an unexplained
difference is a stop condition. This module is what keeps that promise machine-checkable
instead of prose-only: every intentional source of divergence gets one `Divergence` entry,
carrying its status and, where it can be quantified without retraining or re-solving,
its measured effect.

Twelve entries, matching `docs/rebuild_plan.md` §9 one for one (methodology changes 1-4,
`B`-classified defect fixes 5-8 from the §7 register, then 9-12):

 1. IGS GIM day-lookup fix (Table 4 -> here Table 3/4, R1.4)          - measured
 2. Positioning population -> common set of the four `iono` arms      - unmeasurable now
 3. Station recovery, off by default                                  - unmeasurable now
 4. VTEC baseline scored as Laplace rather than Gaussian               - measured
 5. Defect 7, the LR scheduler's parameter source                      - unmeasurable now
 6. Defect 11, elevation cutoff reconciliation (7 deg vs 5 deg)        - unmeasurable now
 7. Defect 17, ensemble seed source                                    - unmeasurable now
 8. Defect 19, Madrigal join tolerance                                 - unmeasurable now
 9. The 10 m outlier boundary, `<` vs `<=`                              - measured
10. The storm/quiet definition, daily vs per-observation                - measured
11. Positioning-coverage canonical variant selection                    - measured
12. Defect 21, Madrigal local_time_hours longitude source                - measured

Two things this module deliberately does NOT do, both by design:

* It does not edit `stec/analysis/*` to make any divergence's "corrected" behaviour the
  default. Where a fix already exists as an opt-in path in a ported module (the scheduler's
  `SchedulerCompat`, the Madrigal loader's `match_nearest` tolerance), this module reads
  that module rather than re-implementing the choice - see each `Divergence.applied` value
  and its `recorded_effect.reason`/`.method` for which module was reused and how.
* It does not touch `PNN_main.tex`. Every number below that differs from a published one is
  reported as a divergence with both values side by side and is explicitly NOT YET APPLIED
  to the manuscript - see `docs/revision/divergences.md`, which is generated by hand from
  this registry's `recorded_effect` values (not auto-written, so the prose explaining each
  number stays reviewable).

Not a numbered `Divergence` entry, because it does not move a published number the way the
ten above do - but stated here anyway, since this is the register a reader auditing
reproducibility claims would check: **best-checkpoint selection and early stopping are not
ported, by decision, not as a remaining gap.** `stec.training.run_training` trains every
epoch a config specifies and saves the final weights; it does not reproduce
`src/training/base_trainer.py`'s selection of the best-validation-loss epoch, which is what
chose each of the ~3,580 published checkpoints. A rebuilt training run therefore converges
to an equivalent model, never a byte-for-byte reproduction of any checkpoint on disk - see
`docs/REPRODUCING.md` (reproducibility table) and `docs/revision/merge_plan.md` (Phase 1,
"what will still not be reproducible") for the same statement.

Two layers of measurement, kept separate on purpose:

* **Pure functions** (`doy_lookup_disagrees`, `count_boundary_rows`,
  `classify_storm_days_daily`, `classify_storm_days_combined`, `interval_coverage`) take
  arrays or small frames and return a number. They do no I/O, so they are exactly what
  `tests/analysis/test_divergences.py` exercises against small synthetic inputs with
  hand-computed answers.
* **`Divergence.measure()`** is the harness itself: a zero-argument callable that re-derives
  the effect from the real, read-only trees this repo already resolves through
  `stec.config.paths` (the OMNI archive, the positioning summaries, the prediction store).
  For the six measurable entries it is real and re-runnable - rerun it after the recovery
  sweep finishes and the numbers may move. #12 is the one exception to "cheap": it re-runs
  a real checkpoint over a real Madrigal day rather than reading a CSV, because no analysis
  stage produces this specific comparison - gated on the checkpoint and Madrigal file being
  present, falling back to the frozen snapshot when they are not (e.g. a worktree without
  `STEC_LEGACY_ROOT` mounted). For the six that cannot be measured without retraining,
  re-solving PPPx, or the running jobs finishing, it always returns the same
  `UnmeasurableEffect`, so calling it is never a silent no-op.

`Divergence.recorded_effect` is the frozen snapshot: what `measure()` returned when this
harness was built (2026-08-21), read directly off already-produced artifacts
(`multiday_results/daily_metrics_rebuilt/summary.csv`,
`multiday_results/uncertainty_calibration_rebuilt/finetuned_stec_own/`,
`multiday_results/storm_stratification_rebuilt/`, the three positioning summary trees, and
- for #12 only - a live seeded run of the real `Finetune_STEC_2024_132` checkpoint over a
real Madrigal day).
It is what `docs/revision/divergences.md` and the tests read, so both stay fast and
reproducible without depending on the 640 GB tree being mounted at import time.
"""

from __future__ import annotations

import logging
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from typing import Literal

import numpy as np
import pandas as pd

from ..config import paths

# --- pure measurement functions -----------------------------------------------------
#
# Each one is small enough to hand-verify and carries no I/O, which is what makes it
# testable against a synthetic input with a hand-computed answer.


def doy_lookup_disagrees(doy: int, total_days: int = 365) -> bool:
    """Reproduce the float32 round-trip that corrupted the GIM day lookup (defect #1).

    `doy` was normalised to `(doy - 1) / total_days` for the model input and inverted in
    float32 when read back from a results frame (`stec/baselines/gim.py`,
    `date_from_year_doy`). Float32 rounding sometimes lands the inverted value just under
    the intended integer (e.g. DOY 189 comes back as 188.99998), so `int()` truncates to
    the *previous* day while `round()` recovers the correct one. Returns whether the two
    disagree for the given `doy`.
    """
    denormalised = _denormalised_doy(doy, total_days)
    return int(denormalised) != round(denormalised)


def _denormalised_doy(doy: int, total_days: int = 365) -> float:
    """The exact float32 forward-then-inverse transform the model input goes through."""
    normalised = np.float32((doy - 1) / total_days)
    return float(normalised * np.float32(total_days) + np.float32(1))


def count_boundary_rows(values: Sequence[float], threshold: float = 10.0) -> int:
    """Count station-days sitting exactly at `threshold` (defect #9).

    These are the only rows that move between a strict `<` (excluded) and a `<=`
    (included) outlier rule - anything not exactly equal to the threshold is treated
    identically by both operators.
    """
    array = np.asarray(values, dtype=float)
    return int(np.count_nonzero(array == threshold))


def classify_storm_days_daily(
    dst_min: pd.Series, threshold: float = -50.0
) -> pd.Series:
    """The positioning (R2.7) storm rule: a day is a storm when its daily minimum Dst
    reaches `threshold` nT."""
    return dst_min <= threshold


def classify_storm_days_combined(
    dst_min: pd.Series,
    kp_max: pd.Series,
    kp_threshold: float = 37.0,
    dst_threshold: float = -33.0,
) -> pd.Series:
    """The per-observation (STEC scenario) storm rule, applied at the day level by taking
    each day's extremes: a day is a storm when its daily max Kp or min Dst crosses the
    threshold. Kp is stored scaled by 10 in the OMNI archive (37 means Kp 3.7)."""
    return (kp_max >= kp_threshold) | (dst_min <= dst_threshold)


def interval_coverage(
    y: np.ndarray, mu: np.ndarray, sigma: np.ndarray, level: float, family: str
) -> float:
    """Empirical fraction of observations inside the central `level` interval under a
    Gaussian or Laplace predictive with the given mean and standard deviation `sigma`
    (defect #4 is scoring a Laplace-trained model's uncertainty as if it were Gaussian).

    Mirrors `stec.analysis.uncertainty_calibration.half_width`, reimplemented here as a
    small standalone function - importing that module's version would work equally well,
    but this keeps the divergence measurable without depending on its streaming
    accumulator machinery for what is, at its core, one closed-form formula.
    """
    if family == "laplace":
        scale = sigma / np.sqrt(2.0)
        half_width = -scale * np.log(1.0 - level)
    elif family == "gaussian":
        from scipy.stats import norm

        half_width = sigma * norm.ppf(0.5 + level / 2)
    else:
        raise ValueError(f"unknown predictive family {family!r}")
    return float(np.mean(np.abs(y - mu) <= half_width))


# --- effect types ---------------------------------------------------------------------


@dataclass(frozen=True)
class Measurement:
    """One reported number: what changed, from what value to what value."""

    label: str
    new_value: float
    unit: str
    old_value: float | None = None  # None when there is no single prior number to cite
    n: int | None = None  # sample size this was measured over, when that is meaningful


@dataclass(frozen=True)
class MeasuredEffect:
    """The quantified outcome of running a divergence's measurement, real numbers from a
    real (read-only) source, tagged with how they were obtained."""

    method: str  # one line: what was read or computed, and from where
    measurements: tuple[Measurement, ...]

    def __post_init__(self) -> None:
        if not self.measurements:
            raise ValueError("a MeasuredEffect must carry at least one Measurement")


@dataclass(frozen=True)
class UnmeasurableEffect:
    """Why this divergence's effect cannot be quantified right now, and what would make
    it quantifiable. Carries no number on purpose - a placeholder number here is exactly
    the fabrication this registry exists to prevent."""

    reason: str
    would_require: str


Effect = MeasuredEffect | UnmeasurableEffect

ApplicationStatus = Literal["applied", "available_but_off", "not_yet_ported"]
EffectStatus = Literal["measured", "unmeasurable_now"]


@dataclass(frozen=True)
class Divergence:
    """One named, deliberate source of divergence between the rebuilt pipeline and the
    submitted paper.

    `applied` and the derived `status` answer two different questions. `applied` is about
    the *code*: does the rebuilt pipeline's default path already produce the changed
    behaviour, does the fix exist only as an opt-in the default path does not take, or
    has nothing been ported yet. `status` is about *this registry*: did measuring the
    effect right now, read-only, produce a number, or not.
    """

    id: str
    description: str
    deliverable: str
    reviewer_comment: str | None
    applied: ApplicationStatus
    recorded_effect: Effect
    measure: Callable[[], Effect]

    def __post_init__(self) -> None:
        if not self.id:
            raise ValueError("a divergence must have a non-empty id")
        if not self.description:
            raise ValueError(f"{self.id}: description must not be empty")
        if not self.deliverable:
            raise ValueError(f"{self.id}: deliverable must not be empty")
        if isinstance(self.recorded_effect, MeasuredEffect):
            for m in self.recorded_effect.measurements:
                if m.new_value is None:
                    raise ValueError(
                        f"{self.id}: measured effect '{m.label}' carries no numeric value"
                    )
        elif isinstance(self.recorded_effect, UnmeasurableEffect):
            if (
                not self.recorded_effect.reason
                or not self.recorded_effect.would_require
            ):
                raise ValueError(
                    f"{self.id}: unmeasurable effect must carry both a reason and what "
                    "measuring it would require"
                )
        else:
            raise TypeError(
                f"{self.id}: unrecognised effect type {type(self.recorded_effect)}"
            )

    @property
    def status(self) -> EffectStatus:
        return (
            "measured"
            if isinstance(self.recorded_effect, MeasuredEffect)
            else "unmeasurable_now"
        )


def _unmeasurable(reason: str, would_require: str) -> UnmeasurableEffect:
    return UnmeasurableEffect(reason=reason, would_require=would_require)


# --- #1: IGS GIM day-lookup fix ---------------------------------------------------------


def _measure_gim_day_lookup() -> Effect:
    """Recompute which days the bug hits (cheap, pure), and read the already-recomputed
    Table 3/4 IGS GIM rows from `analyses/daily_metrics/rebuilt/summary.csv` if that
    artifact is on disk; otherwise fall back to the recorded snapshot below, since
    re-running `daily_metrics` from scratch is a store-scale operation, not a read.
    """
    affected = [d for d in range(1, 367) if doy_lookup_disagrees(d)]
    summary_path = (
        paths.analysis_result_dir("daily_metrics", rebuilt=True) / "summary.csv"
    )
    table3, table4 = (
        8.2826,
        15.4519,
    )  # the recorded snapshot; see _GIM_DAY_LOOKUP_EFFECT
    if summary_path.exists():
        frame = pd.read_csv(summary_path)
        own = frame[
            (frame["dataset"] == "own_vtec_gim") & (frame["Model"] == "IGS GIM")
        ]
        madrigal = frame[
            (frame["dataset"] == "madrigal_vtec_gim") & (frame["Model"] == "IGS GIM")
        ]
        if len(own):
            table3 = float(own["RMSE_mean"].iloc[0])
        if len(madrigal):
            table4 = float(madrigal["RMSE_mean"].iloc[0])
    return MeasuredEffect(
        method=(
            f"{len(affected)} of 365 days/year corrupted by int() truncation (verified by "
            "replaying the exact float32 normalise/denormalise round-trip); current IGS "
            "GIM RMSE read from daily_metrics_rebuilt/summary.csv (falls back to the "
            "recorded 2026-08-20 snapshot if that file is absent)."
        ),
        measurements=(
            Measurement(
                "Table 3, own dataset, IGS GIM RMSE_mean",
                old_value=8.56,
                new_value=round(table3, 4),
                unit="TECU",
                n=242,
            ),
            Measurement(
                "Table 4, Madrigal dataset, IGS GIM RMSE_mean",
                old_value=15.64,
                new_value=round(table4, 4),
                unit="TECU",
                n=235,
            ),
        ),
    )


_GIM_DAY_LOOKUP_EFFECT = MeasuredEffect(
    method=(
        "26 of 365 days/year corrupted by int() truncation of a float32-denormalised doy "
        "(DOY 8, 15, 24, 29, 47-48, 57-58, 93-95, 113-115, 184-189, 225-230 - reproduced by "
        "replaying the exact normalise/inverse transform in `doy_lookup_disagrees`, matching "
        "the 26-day count and 184-189/225-230 range already recorded in CLAUDE.md). "
        "Current IGS GIM RMSE read from multiday_results/daily_metrics_rebuilt/summary.csv, "
        "recorded 2026-08-20, which already runs `date_from_year_doy`'s round()-based fix."
    ),
    measurements=(
        Measurement(
            "Table 3, own dataset, IGS GIM RMSE_mean",
            old_value=8.56,
            new_value=8.2826,
            unit="TECU",
            n=242,
        ),
        Measurement(
            "Table 4, Madrigal dataset, IGS GIM RMSE_mean",
            old_value=15.64,
            new_value=15.4519,
            unit="TECU",
            n=235,
        ),
    ),
)


# --- #4: VTEC baseline scored as Laplace rather than Gaussian --------------------------


def _measure_vtec_family() -> Effect:
    """Read the already-produced coverage table
    (`analyses/uncertainty_calibration/rebuilt/finetuned_stec_own/coverage.csv`) if
    present; otherwise fall back to the recorded snapshot. Recomputing from scratch means
    streaming the 9.5 M-row `own` test-set partition of the prediction store, which is
    cheap enough to do (`python -m stec.analysis.uncertainty_calibration`) but not
    something this function does implicitly on every call.
    """
    coverage_path = (
        paths.analysis_result_dir("uncertainty_calibration", rebuilt=True)
        / "finetuned_stec_own"
        / "coverage.csv"
    )
    if not coverage_path.exists():
        return _VTEC_FAMILY_EFFECT
    frame = pd.read_csv(coverage_path)
    row = frame[
        (frame["model"] == "VTEC + Mapping") & np.isclose(frame["nominal"], 0.5)
    ]
    gaussian = float(row[row["family"] == "gaussian"]["empirical"].iloc[0])
    laplace = float(row[row["family"] == "laplace"]["empirical"].iloc[0])
    n = 9_475_585
    return MeasuredEffect(
        method=(
            "Read multiday_results/uncertainty_calibration_rebuilt/finetuned_stec_own/"
            "coverage.csv (produced by `stec.analysis.uncertainty_calibration`, which "
            "scores every product under both families and tags which is native)."
        ),
        measurements=(
            Measurement(
                "VTEC + Mapping empirical coverage at nominal 50%, scored Gaussian "
                "(mis-specified)",
                new_value=round(100 * gaussian, 2),
                unit="% coverage",
                n=n,
            ),
            Measurement(
                "VTEC + Mapping empirical coverage at nominal 50%, scored Laplace (native)",
                new_value=round(100 * laplace, 2),
                unit="% coverage",
                n=n,
            ),
        ),
    )


_VTEC_FAMILY_EFFECT = MeasuredEffect(
    method=(
        "Read multiday_results/uncertainty_calibration_rebuilt/finetuned_stec_own/"
        "coverage.csv, recorded 2026-08-20 (242 days, 9,475,585 observations)."
    ),
    measurements=(
        Measurement(
            "VTEC + Mapping empirical coverage at nominal 50%, scored Gaussian "
            "(mis-specified)",
            new_value=85.91,
            unit="% coverage",
            n=9_475_585,
        ),
        Measurement(
            "VTEC + Mapping empirical coverage at nominal 50%, scored Laplace (native)",
            new_value=76.67,
            unit="% coverage",
            n=9_475_585,
        ),
    ),
)


# --- #9: the 10 m outlier boundary ------------------------------------------------------


def _measure_outlier_boundary() -> Effect:
    """Count real station-days at exactly the 10.0 m boundary across the three source
    trees `stec.analysis.common_set_positioning` reads: the published three-way tree, the
    weighting ablation, and the pretrained elevation arm's per-day summaries."""
    from .common_set_positioning import (
        ARM_LABELS,
        COLUMNS,
        DEFAULT_EXPERIMENT,
        load_pretrained_elev,
    )
    from .positioning_summary import (
        DEFAULT_WEIGHTING_SUMMARY,
        canonical_positioning_summary,
    )

    sources = {
        "three_way": canonical_positioning_summary(),
        "ablation": DEFAULT_WEIGHTING_SUMMARY,
    }
    total_rows = 0
    total_boundary = 0
    for path in sources.values():
        if not path.exists():
            return _OUTLIER_BOUNDARY_EFFECT
        frame = pd.read_csv(path, usecols=lambda c: c in COLUMNS)
        frame = frame[frame["method"].isin(ARM_LABELS)]
        total_rows += len(frame)
        total_boundary += count_boundary_rows(frame["error_3d_rms"])

    elev = load_pretrained_elev(DEFAULT_EXPERIMENT)
    total_rows += len(elev)
    if len(elev):
        total_boundary += count_boundary_rows(elev["error_3d_rms"])

    return MeasuredEffect(
        method=(
            "Counted error_3d_rms == 10.0 across positioning_comparison_3way, "
            "positioning_20260216_2052 and the pretrained-elevation per-day summaries - "
            "the same three trees stec.analysis.common_set_positioning reads."
        ),
        measurements=(
            Measurement(
                "station-day rows at exactly 10.000 m (move between `<` and `<=`)",
                new_value=total_boundary,
                unit="rows",
                n=total_rows,
            ),
        ),
    )


_OUTLIER_BOUNDARY_EFFECT = MeasuredEffect(
    method=(
        "Counted error_3d_rms == 10.0 across positioning_comparison_3way (35,652 rows), "
        "positioning_20260216_2052 (56,457 rows) and the pretrained-elevation per-day "
        "summaries (8,350 rows), recorded 2026-08-21. Nearest approach to the boundary "
        "in either direction: 9.9624 m and 10.0236 m - several centimetres away, not a "
        "rounding artefact away."
    ),
    measurements=(
        Measurement(
            "station-day rows at exactly 10.000 m (move between `<` and `<=`)",
            new_value=0,
            unit="rows",
            n=100_459,
        ),
    ),
)


# --- #10: the storm/quiet definition -----------------------------------------------------


def _measure_storm_definition() -> Effect:
    """Count storm days under both rules over the real OMNI archive (full 2024, 366 days,
    independent of positioning coverage), and, where the positioning summary is on disk,
    the quiet/storm improvement over IGS GIM under each rule (reusing
    `stec.analysis.storm_stratification`'s building blocks, not its fixed threshold)."""
    from ..positioning import metrics as pm
    from . import storm_stratification as ss

    if not paths.OMNI_INDICES.exists():
        return _STORM_DEFINITION_EFFECT

    indices = ss.load_daily_geomagnetic_indices(2024, paths.OMNI_INDICES)
    daily_storm = classify_storm_days_daily(indices["dst_min"])
    combined_storm = classify_storm_days_combined(indices["dst_min"], indices["kp_max"])
    measurements = [
        Measurement(
            "storm days, full 2024 OMNI archive, daily Dst<=-50 nT",
            new_value=int(daily_storm.sum()),
            unit="days",
            n=len(indices),
        ),
        Measurement(
            "storm days, full 2024 OMNI archive, combined Kp>=37 or Dst<=-33",
            new_value=int(combined_storm.sum()),
            unit="days",
            n=len(indices),
        ),
    ]

    summary_path = ss.canonical_positioning_summary()
    if summary_path.exists():
        positions = pd.read_csv(summary_path)
        merged = positions.merge(indices, on="doy", how="left").dropna(
            subset=["dst_min"]
        )
        merged = pm.exclude_outlier_station_days(merged)
        merged["Method"] = (
            merged["method"].map(ss.METHOD_LABELS).fillna(merged["method"])
        )

        for rule_name, is_storm in (
            ("daily Dst<=-50", classify_storm_days_daily(merged["dst_min"])),
            (
                "combined Kp>=37 or Dst<=-33",
                classify_storm_days_combined(merged["dst_min"], merged["kp_max"]),
            ),
        ):
            regime = merged.assign(regime=np.where(is_storm, "storm", "quiet"))
            by_regime = pm.summarise(regime, ["Method", "regime"])
            means = by_regime["3D_mean_m"].unstack("regime")
            baseline = means.loc[ss.GIM_LABEL]
            gain = 100 * (baseline - means.loc["Direct STEC"]) / baseline
            measurements.append(
                Measurement(
                    f"Direct STEC improvement over IGS GIM, quiet, {rule_name}",
                    new_value=round(float(gain["quiet"]), 3),
                    unit="%",
                )
            )
            measurements.append(
                Measurement(
                    f"Direct STEC improvement over IGS GIM, storm, {rule_name}",
                    new_value=round(float(gain["storm"]), 3),
                    unit="%",
                )
            )

    return MeasuredEffect(
        method=(
            "Applied both rules to the daily Dst_min/Kp_max extremes read from "
            "data/omni_hourly_2010-2025.h5, then joined to the positioning summary "
            "(exclude_outlier_station_days applied first) to get the improvement under "
            "each rule."
        ),
        measurements=tuple(measurements),
    )


_STORM_DEFINITION_EFFECT = MeasuredEffect(
    method=(
        "Applied both rules to the daily Dst_min/Kp_max extremes read from "
        "data/omni_hourly_2010-2025.h5 (full 2024, 366 days) and to the 242-day "
        "positioning test period (positioning_comparison_3way, after the 10 m outlier "
        "rule), recorded 2026-08-21."
    ),
    measurements=(
        Measurement(
            "storm days, full 2024 OMNI archive, daily Dst<=-50 nT",
            new_value=52,
            unit="days",
            n=366,
        ),
        Measurement(
            "storm days, full 2024 OMNI archive, combined Kp>=37 or Dst<=-33",
            new_value=132,
            unit="days",
            n=366,
        ),
        Measurement(
            "storm days, 242-day positioning test period, daily Dst<=-50 nT",
            new_value=39,
            unit="days",
            n=242,
        ),
        Measurement(
            "storm days, 242-day positioning test period, combined Kp>=37 or Dst<=-33",
            new_value=102,
            unit="days",
            n=242,
        ),
        Measurement(
            "Direct STEC improvement over IGS GIM, quiet, daily Dst<=-50 (published rule)",
            old_value=31.9,
            new_value=31.879,
            unit="%",
        ),
        Measurement(
            "Direct STEC improvement over IGS GIM, storm, daily Dst<=-50 (published rule)",
            old_value=26.3,
            new_value=26.264,
            unit="%",
        ),
        Measurement(
            "Direct STEC improvement over IGS GIM, quiet, combined Kp>=37 or Dst<=-33",
            new_value=32.237,
            unit="%",
        ),
        Measurement(
            "Direct STEC improvement over IGS GIM, storm, combined Kp>=37 or Dst<=-33",
            new_value=29.127,
            unit="%",
        ),
    ),
)


# --- the six that cannot be measured right now ------------------------------------------


def _measure_positioning_population() -> Effect:
    return _POSITIONING_POPULATION_EFFECT


_POSITIONING_POPULATION_EFFECT = _unmeasurable(
    reason=(
        "stec.analysis.common_set_positioning already computes the common-set population "
        "and its N, but the count depends on which station-days PPPx solved under every "
        "iono arm, and `recovery-models` (plus the elev pass over recovered station-days, "
        "rebuild_plan.md §10 phase 6) is still mid-sweep. rebuild_status.md records 3,733 "
        "files under experiments/ changing in the nine hours after the checked-in "
        "coverage.csv snapshot was taken - a count read now would be a torn snapshot, not "
        "a stable N."
    ),
    would_require=(
        "Wait for recovery-models and recovery-geometry to finish (systemctl --user "
        "is-active, per CLAUDE.md/rebuild_plan.md §0), then run "
        "`python -m stec.analysis.common_set_positioning` against the settled tree and "
        "report both the published Table 5 N and the common-set N side by side."
    ),
)


def _measure_station_recovery() -> Effect:
    return _STATION_RECOVERY_EFFECT


_STATION_RECOVERY_EFFECT = _unmeasurable(
    reason=(
        "Station recovery is a declared stage, optional and off by default (rebuild_plan.md "
        "§2). Measuring its sensitivity means comparing positioning with the recovered "
        "station-days included against the database-only default, and the sweep that "
        "produces those extra station-days (recovery-models, recovery-geometry) is still "
        "running - the population it would add is not yet finalised."
    ),
    would_require=(
        "Wait for the recovery sweep to finish, then run positioning with the recovery "
        "stage on and off over the same day set and diff Table 5 / the appendix table."
    ),
)


def _measure_defect7_scheduler() -> Effect:
    return _DEFECT7_SCHEDULER_EFFECT


_DEFECT7_SCHEDULER_EFFECT = _unmeasurable(
    reason=(
        "stec/training/schedulers.py already ports both paths as `SchedulerCompat.LEGACY` "
        "(byte-for-byte the original wrong parameter source, and the default - matching "
        "the ~3,580 existing checkpoints) and `.CORRECTED`. But the difference is a "
        "training-time LR trajectory, not a number derivable from an existing checkpoint: "
        "measuring it means training under both, which is Gate C (rebuild_plan.md §8), "
        "and Gate C has not been run in this worktree."
    ),
    would_require=(
        "Retrain one STEC fine-tune day and one VTEC fine-tune day under "
        "SchedulerCompat.LEGACY and .CORRECTED, deterministic mode forced, same seed, and "
        "diff the loss curves and final test metrics."
    ),
)


def _measure_defect11_elevation_cutoff() -> Effect:
    return _DEFECT11_ELEVATION_CUTOFF_EFFECT


_DEFECT11_ELEVATION_CUTOFF_EFFECT = _unmeasurable(
    reason=(
        "No corrections-generation or PPPx-config code has been ported into stec/ yet - "
        "`stec/positioning/metrics.py`'s own docstring records the three unreconciled "
        "values (7 deg PPPx elev_mask, 5 deg reference-correction generation, 5 deg "
        "Madrigal loader) and states it deliberately adds no cutoff parameter, since a "
        "`.pos` file already reflects whichever mask solved it. Reconciling them changes "
        "which observations enter positioning and the STEC comparison, which needs "
        "re-inference and, for positioning, a PPPx re-run."
    ),
    would_require=(
        "Port the corrections-generation stage, pick and justify one cutoff value, "
        "re-run the STEC comparison and PPPx over a sample of days at that cutoff, and "
        "diff Tables 3-5 against the current three-way-cutoff numbers."
    ),
)


def _measure_defect17_ensemble_seed() -> Effect:
    return _DEFECT17_ENSEMBLE_SEED_EFFECT


_DEFECT17_ENSEMBLE_SEED_EFFECT = _unmeasurable(
    reason=(
        "No ensemble-model code has been ported into stec/models yet (only "
        "architectures.py, capabilities.py and determinism.py exist there). Even once "
        "ported, the effect of `config['random_seed']` vs the hardcoded 42 is only visible "
        "by retraining ensemble members under each and comparing predictions - it is not "
        "recoverable from an existing artifact."
    ),
    would_require=(
        "Port the ensemble path, retrain its members under both seed sources, and diff "
        "the resulting ensemble predictions and any metric that depends on them."
    ),
)


def _measure_defect19_madrigal_tolerance() -> Effect:
    return _DEFECT19_MADRIGAL_TOLERANCE_EFFECT


_DEFECT19_MADRIGAL_TOLERANCE_EFFECT = _unmeasurable(
    reason=(
        "stec/baselines/madrigal.py already ports `match_nearest(lat_lon_tolerance_deg=...)` "
        "as a true, symmetric tolerance on the join key, defaulting to 0.0 (delegates to "
        "the legacy exact-bin join, `match_exact_key`, which is what produced the published "
        "numbers). But sweeping tolerance to measure its effect on Table 4 means re-running "
        "the join over the full Madrigal comparison (740 GB, per-station) and then "
        "recomputing `madrigal_reference_offset` on each newly-matched population, since "
        "that decomposition depends on the join - out of scope for 'cheap and safe right "
        "now'."
    ),
    would_require=(
        "Run match_nearest at a few tolerance values over the real Madrigal/own-test-set "
        "join, rerun madrigal_reference_offset on each matched population, and diff "
        "Table 4's Madrigal rows and match_rate."
    ),
)


_VARIANT_SELECTION_EFFECT = MeasuredEffect(
    method=(
        "Ran stec.analysis.positioning_coverage against the repaired tree with no sweep "
        "writing to it, 2026-08-21, and read the collision table it writes."
    ),
    measurements=(
        Measurement(
            "DOYs matched by more than one experiment directory",
            new_value=0,
            unit="DOYs",
            old_value=31,
        ),
        Measurement(
            "station-days solved by all methods, iono weighting",
            new_value=7885,
            unit="station-days",
            old_value=8003,
            n=10851,
        ),
    ),
)


def _measure_variant_selection() -> Effect:
    """Read the collision table `positioning_coverage` writes, if a run is on disk.

    The number that matters is how many station-days were attributed to a model that did
    not produce them, and that is exactly what `collisions.csv` counts. Recomputing it
    here would mean re-globbing every experiment tree, so this reads the artifact instead
    and says so when there is none.
    """
    import pandas as pd

    from ..config import paths

    # The rebuilt stage writes to analyses/positioning_coverage/rebuilt/; the pre-rebuild
    # script wrote to .../pre_rebuild/ (docs/revision/results_layout.md - nested since the
    # results-layout restructure, replacing the flat positioning_coverage_rebuilt /
    # positioning_coverage top-level names). Prefer the rebuilt table, since it is the one
    # that selects the canonical variant at all.
    candidates = (
        paths.LEGACY_MULTIDAY
        / "analyses"
        / "positioning_coverage"
        / "rebuilt"
        / "collisions.csv",
        paths.LEGACY_MULTIDAY
        / "analyses"
        / "positioning_coverage"
        / "pre_rebuild"
        / "collisions.csv",
    )
    collisions = next((c for c in candidates if c.exists()), None)
    if collisions is None:
        return UnmeasurableEffect(
            reason=f"no collision table on disk; looked in {[str(c) for c in candidates]}",
            would_require="a run of stec.analysis.positioning_coverage",
        )
    table = pd.read_csv(collisions)
    doys = int(table["doy"].nunique()) if len(table) else 0
    return MeasuredEffect(
        method=f"Read {collisions}, written by stec.analysis.positioning_coverage.",
        measurements=(
            Measurement(
                "station-days attributed to a non-canonical variant",
                new_value=float(len(table)),
                unit="station-days",
                old_value=None,
            ),
            Measurement(
                "DOYs matched by more than one experiment directory",
                new_value=float(doys),
                unit="DOYs",
                old_value=31.0,
            ),
        ),
    )


# --- #12: Madrigal local_time_hours longitude source (defect 21) -----------------------

_MADRIGAL_LOCAL_TIME_CHECKPOINT = paths.LEGACY_EXPERIMENTS / (
    "Finetune_STEC_2024_132_BayesianResNetSTEC_h1024_l4_nh4_v128x4_g32x2_lr2e-4_bs512_"
    "GNLL_Adam_ReduceLROnPlateau_sub500K_SH5_ps0.1_kl5w0.1_lw1e-1_SWI"
)
_MADRIGAL_LOCAL_TIME_YEAR_DOY = (2024, 132)
_MADRIGAL_LOCAL_TIME_SAMPLE_SIZE = 20_000
_MADRIGAL_LOCAL_TIME_SEED = 42


def _measure_madrigal_local_time_convention() -> Effect:
    """Re-run the paper's real DOY-132 STEC checkpoint over a real Madrigal day, once under
    each `local_time_hours` convention, and report how far the mean prediction moves.

    Unlike the six `UnmeasurableEffect` entries, this needs no retraining or PPPx re-run -
    the checkpoint and the Madrigal day file are both external, immutable data already on
    disk in a full checkout, so it recomputes live rather than only ever returning the
    frozen snapshot. Falls back to the snapshot when either file is absent (e.g. a worktree
    without `STEC_LEGACY_ROOT` mounted) rather than failing, matching
    `_measure_gim_day_lookup`'s fallback pattern.

    Subsamples the day (`_MADRIGAL_LOCAL_TIME_SAMPLE_SIZE` of ~2.0 M rows) to keep this a
    CPU forward pass rather than a full-day run, and pins the Bayesian output layer's
    weights identically for both conventions (`stec.models.determinism.frozen`) so the
    delta isolates the input change from sampling noise - checked by a same-input
    zero-perturbation control that must return exactly 0.0 before anything below is
    trusted (the CLAUDE.md Bayesian A/B invariant; a comparison built without it once
    measured 1.4 TECU of pure sampling noise and used it to reject a correct approach).
    """
    checkpoint = (
        _MADRIGAL_LOCAL_TIME_CHECKPOINT
        / "model"
        / ("finetune_BayesianResNetSTEC_seed42.pth")
    )
    config_path = _MADRIGAL_LOCAL_TIME_CHECKPOINT / "config.yaml"
    year, doy = _MADRIGAL_LOCAL_TIME_YEAR_DOY
    madrigal_file = paths.madrigal_day(year, 5, 11)  # 2024-05-11 == DOY 132
    if not (checkpoint.exists() and config_path.exists() and madrigal_file.exists()):
        return _MADRIGAL_LOCAL_TIME_EFFECT

    import torch  # noqa: PLC0415 - heavy, optional dependency; keep module import light
    import yaml  # noqa: PLC0415

    from ..data.day_reader import compute_local_time_hours  # noqa: PLC0415
    from ..data.madrigal_reader import read_madrigal_day  # noqa: PLC0415
    from ..inference.run_inference import (  # noqa: PLC0415
        _numeric_tensors,
        build_layout_and_assembler,
    )
    from ..models import determinism  # noqa: PLC0415
    from ..models.architectures import load_checkpoint  # noqa: PLC0415

    config = yaml.safe_load(config_path.read_text())
    layout, assembler = build_layout_and_assembler(config)
    model, shape = load_checkpoint(checkpoint, map_location="cpu")
    if shape["n_in"] != layout.total_dim:
        return _MADRIGAL_LOCAL_TIME_EFFECT

    raw = read_madrigal_day(year, doy, split="test", with_identity=False)
    n_total = len(raw["stec"])
    rng = np.random.default_rng(0)
    sample_size = min(_MADRIGAL_LOCAL_TIME_SAMPLE_SIZE, n_total)
    idx = np.sort(rng.choice(n_total, size=sample_size, replace=False))
    sample = {name: values[idx] for name, values in raw.items()}

    lt_ipp = compute_local_time_hours(
        sample["sod"].astype(np.float64), sample["lon_ipp"].astype(np.float64)
    ).astype(np.float32)
    lt_station = compute_local_time_hours(
        sample["sod"].astype(np.float64), sample["lon_sta"].astype(np.float64)
    ).astype(np.float32)
    inputs_ipp = assembler.assemble(
        _numeric_tensors({**sample, "local_time_hours": lt_ipp})
    )
    inputs_station = assembler.assemble(
        _numeric_tensors({**sample, "local_time_hours": lt_station})
    )

    seed = _MADRIGAL_LOCAL_TIME_SEED
    with determinism.frozen(model, seed=seed):
        torch.manual_seed(seed)
        with torch.no_grad():
            control_a, _ = model(inputs_ipp)
        torch.manual_seed(seed)
        with torch.no_grad():
            control_b, _ = model(inputs_ipp)
        control = float((control_a - control_b).abs().max())
        if control != 0.0:
            return _unmeasurable(
                reason=(
                    f"zero-perturbation control returned {control}, not exactly 0.0 in "
                    "this environment - the pinned-weights invariant "
                    "(stec.models.determinism.frozen) does not hold here"
                ),
                would_require="an environment where determinism.frozen pins weights exactly",
            )

        torch.manual_seed(seed)
        with torch.no_grad():
            mean_ipp, _ = model(inputs_ipp)
        torch.manual_seed(seed)
        with torch.no_grad():
            mean_station, _ = model(inputs_station)

    delta = (mean_ipp - mean_station).squeeze(-1).numpy()
    return MeasuredEffect(
        method=(
            f"Ran the real Finetune_STEC_2024_{doy} (lr2e-4_bs512, paper variant) "
            f"checkpoint over a {sample_size:,}-row seed-0 subsample of the real "
            f"{year}-{doy:03d} Madrigal test-station day ({n_total:,} rows total, "
            "elev >= 5 deg), once with local_time_hours from lon_ipp and once from "
            f"lon_sta, weights pinned identically (seed {seed}) so the delta isolates the "
            "input change; zero-perturbation control on identical input returned exactly "
            "0.0."
        ),
        measurements=(
            Measurement(
                "predicted STEC, IPP-longitude minus station-longitude convention: mean",
                new_value=round(float(delta.mean()), 4),
                unit="TECU",
                n=sample_size,
            ),
            Measurement(
                "predicted STEC, IPP-longitude minus station-longitude convention: RMSE",
                new_value=round(float(np.sqrt(np.mean(delta**2))), 4),
                unit="TECU",
                n=sample_size,
            ),
            Measurement(
                "predicted STEC, IPP-longitude minus station-longitude convention: "
                "max|delta|",
                new_value=round(float(np.abs(delta).max()), 4),
                unit="TECU",
                n=sample_size,
            ),
        ),
    )


_MADRIGAL_LOCAL_TIME_EFFECT = MeasuredEffect(
    method=(
        "Ran the real Finetune_STEC_2024_132 (lr2e-4_bs512, paper variant) checkpoint over "
        "a 20,000-row seed-0 subsample of the real 2024-05-11 (DOY 132) Madrigal "
        "test-station day (2,036,669 rows total, elev >= 5 deg), once with "
        "local_time_hours from lon_ipp and once from lon_sta, weights pinned identically "
        "(seed 42) so the delta isolates the input change; zero-perturbation control on "
        "identical input returned exactly 0.0. Recorded 2026-08-21."
    ),
    measurements=(
        Measurement(
            "predicted STEC, IPP-longitude minus station-longitude convention: mean",
            new_value=0.0015,
            unit="TECU",
            n=20_000,
        ),
        Measurement(
            "predicted STEC, IPP-longitude minus station-longitude convention: RMSE",
            new_value=0.8011,
            unit="TECU",
            n=20_000,
        ),
        Measurement(
            "predicted STEC, IPP-longitude minus station-longitude convention: max|delta|",
            new_value=13.4411,
            unit="TECU",
            n=20_000,
        ),
    ),
)


# --- the registry ------------------------------------------------------------------------

REGISTRY: tuple[Divergence, ...] = (
    Divergence(
        id="1",
        description=(
            "IGS GIM day-lookup fix: int() truncation of a float32-denormalised doy "
            "silently loaded the previous day's IONEX map on 26 of 365 days/year; "
            "round() (stec/baselines/gim.py::date_from_year_doy) fixes it."
        ),
        deliverable="Table 3 (own dataset, IGS GIM row), Table 4 (Madrigal dataset, IGS GIM row)",
        reviewer_comment="R1.4",
        applied="applied",
        recorded_effect=_GIM_DAY_LOOKUP_EFFECT,
        measure=_measure_gim_day_lookup,
    ),
    Divergence(
        id="2",
        description=(
            "Positioning population: Table 5 moves from the published per-arm "
            "populations to the common set of station-days solved under all four "
            "`iono` arms (stec.analysis.common_set_positioning)."
        ),
        deliverable="Table 5, appendix Table A1",
        reviewer_comment="R1.5",
        applied="available_but_off",
        recorded_effect=_POSITIONING_POPULATION_EFFECT,
        measure=_measure_positioning_population,
    ),
    Divergence(
        id="3",
        description=(
            "Station recovery (RINEX-based geometry recovery for station-days absent "
            "from the STEC database): a declared stage, optional, off by default - "
            "reported as a sensitivity, not folded into the default population."
        ),
        deliverable="Table 5, appendix Table A1 (sensitivity only)",
        reviewer_comment="R1.5",
        applied="available_but_off",
        recorded_effect=_STATION_RECOVERY_EFFECT,
        measure=_measure_station_recovery,
    ),
    Divergence(
        id="4",
        description=(
            "The VTEC baseline (Mao et al. MLP, LaplacianNLL) is scored under its "
            "native Laplace predictive rather than assumed Gaussian; the same stored "
            "uncertainty column reads different coverage under each."
        ),
        deliverable="Uncertainty calibration diagnostics (R1.6), any VTEC coverage claim",
        reviewer_comment="R1.6",
        applied="applied",
        recorded_effect=_VTEC_FAMILY_EFFECT,
        measure=_measure_vtec_family,
    ),
    Divergence(
        id="5",
        description=(
            "Defect 7: the LR scheduler's *parameters* (not its type selection) are "
            "read from config['pretrain'] regardless of training mode. "
            "stec/training/schedulers.py ports both as SchedulerCompat.LEGACY "
            "(default, matches existing checkpoints) and .CORRECTED."
        ),
        deliverable="Any retrained model (fine-tune schedules; not reused checkpoints)",
        reviewer_comment=None,
        applied="available_but_off",
        recorded_effect=_DEFECT7_SCHEDULER_EFFECT,
        measure=_measure_defect7_scheduler,
    ),
    Divergence(
        id="6",
        description=(
            "Defect 11: elevation cutoffs never reconciled across the pipeline "
            "(7 deg PPPx elev_mask vs 5 deg reference-correction generation vs 5 deg "
            "Madrigal loader threshold)."
        ),
        deliverable="Tables 3-5 (which observations enter STEC comparison and positioning)",
        reviewer_comment=None,
        applied="not_yet_ported",
        recorded_effect=_DEFECT11_ELEVATION_CUTOFF_EFFECT,
        measure=_measure_defect11_elevation_cutoff,
    ),
    Divergence(
        id="7",
        description=(
            "Defect 17: ensemble base seed hardcoded to 42 independent of "
            "config['random_seed']."
        ),
        deliverable="Any ensemble result",
        reviewer_comment=None,
        applied="not_yet_ported",
        recorded_effect=_DEFECT17_ENSEMBLE_SEED_EFFECT,
        measure=_measure_defect17_ensemble_seed,
    ),
    Divergence(
        id="8",
        description=(
            "Defect 19: the Madrigal join used exact equality on rounded integer "
            "position keys, no tolerance, silent misses. "
            "stec/baselines/madrigal.py ports a true tolerance via match_nearest, "
            "defaulting to 0.0 (delegates to the legacy exact join)."
        ),
        deliverable="Table 4 (Madrigal rows), madrigal_reference_offset",
        reviewer_comment=None,
        applied="available_but_off",
        recorded_effect=_DEFECT19_MADRIGAL_TOLERANCE_EFFECT,
        measure=_measure_defect19_madrigal_tolerance,
    ),
    Divergence(
        id="9",
        description=(
            "The 10 m outlier boundary: common_set_positioning applied it with a "
            "strict `<` while positioning_summary and oracle_benchmark used `<=`. "
            "Unified to `<=` in stec.positioning.metrics.exclude_outlier_station_days."
        ),
        deliverable="Table 5, appendix Table A1, oracle_benchmark",
        reviewer_comment=None,
        applied="applied",
        recorded_effect=_OUTLIER_BOUNDARY_EFFECT,
        measure=_measure_outlier_boundary,
    ),
    Divergence(
        id="10",
        description=(
            "Storm/quiet definition: daily min Dst<=-50 nT (positioning, R2.7) vs "
            "per-observation Kp>=37 or Dst<=-33 (STEC scenarios). Two definitions for "
            "two questions, kept deliberately distinct rather than unified."
        ),
        deliverable="Table 5 storm/quiet split (R2.7); STEC scenario stratification",
        reviewer_comment="R2.7",
        applied="applied",
        recorded_effect=_STORM_DEFINITION_EFFECT,
        measure=_measure_storm_definition,
    ),
    Divergence(
        id="11",
        description=(
            "Canonical variant selection in positioning coverage: the pre-rebuild glob "
            "matched every hyperparameter variant on disk and resolved collisions with "
            "drop_duplicates(keep='first') on sorted order, so 'lr1e-4' won over the "
            "paper's 'lr2e-4_bs512' purely alphabetically. "
            "stec.analysis.positioning_coverage selects the canonical variant explicitly "
            "and reports what it excluded (--all-variants restores the broad glob)."
        ),
        deliverable="R1.5 station-day coverage counts",
        reviewer_comment="R1.5",
        applied="applied",
        recorded_effect=_VARIANT_SELECTION_EFFECT,
        measure=_measure_variant_selection,
    ),
    Divergence(
        id="12",
        description=(
            "Defect 21: MadrigalSTECDataset._add_local_time derives local_time_hours from "
            "station longitude (lon_sta), not IPP longitude (lon_ipp) - the convention "
            "src/data_loader/datasets.py established and commented two months earlier for "
            "the 'own' dataset ('Use IPP longitude for local time'). No comment or commit "
            "explains the Madrigal choice; it reads as an oversight, not a requirement. "
            "stec.data.madrigal_reader.read_madrigal_day keeps lon_sta as the default "
            "(local_time_longitude='station') to reproduce the published Table 4 numbers "
            "and the 235 days already in predictions/finetuned_stec/madrigal/; "
            "local_time_longitude='ipp' is the explicit, off-by-default path to the 'own' "
            "dataset's convention for a future harmonised re-run."
        ),
        deliverable=(
            "Table 4 (Madrigal dataset rows), predictions/finetuned_stec/madrigal/ "
            "(235 days), any future Madrigal re-run"
        ),
        reviewer_comment=None,
        applied="applied",
        recorded_effect=_MADRIGAL_LOCAL_TIME_EFFECT,
        measure=_measure_madrigal_local_time_convention,
    ),
)


def by_id(id_: str) -> Divergence:
    for divergence in REGISTRY:
        if divergence.id == id_:
            return divergence
    raise KeyError(f"no divergence registered with id {id_!r}")


def _check_unique_ids(registry: tuple[Divergence, ...] = REGISTRY) -> None:
    seen: set[str] = set()
    for divergence in registry:
        if divergence.id in seen:
            raise ValueError(f"duplicate divergence id {divergence.id!r}")
        seen.add(divergence.id)


_check_unique_ids()


def main() -> None:
    """Print the registry status - id, status, applied, and effect summary - without
    writing anything. `docs/revision/divergences.md` is the prose version of this."""
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    for divergence in REGISTRY:
        print(f"\n=== #{divergence.id}: {divergence.description}")
        print(f"    deliverable: {divergence.deliverable}")
        print(f"    reviewer comment: {divergence.reviewer_comment or '-'}")
        print(f"    applied: {divergence.applied}   status: {divergence.status}")
        effect = divergence.recorded_effect
        if isinstance(effect, MeasuredEffect):
            print(f"    method: {effect.method}")
            for m in effect.measurements:
                old = f"{m.old_value} -> " if m.old_value is not None else ""
                n = f" (n={m.n:,})" if m.n is not None else ""
                print(f"      {m.label}: {old}{m.new_value} {m.unit}{n}")
        else:
            print(f"    reason: {effect.reason}")
            print(f"    would require: {effect.would_require}")


if __name__ == "__main__":
    main()
